### ISSUE TITLE
science-litterate question mis-scoring

### ISSUE THREAD

**Issue by LeVieuxGildas** [benjaffe/chrome-okc-plugin#159] opened 2015-12-31 03:21 UTC
For the "what is bigger ? sun or earth ?" question, people answering "the sun" are wrongly scored as science illiterate. See the red dot in the picture, which should be green.

![bigger](https://cloud.githubusercontent.com/assets/2790889/12060611/8fe2f6be-af41-11e5-930d-a106df539f38.png)

**Comment by stn4d89** [comment] 2015-12-31 03:30
YUP!!!!
Chasing that one big time. 
There are two identically-worded q's. I am not sure if that is the cause, but I am trying to identify the cause.

**Comment by benjaffe** [comment] 2016-02-14 02:10
Looks like it was caused by the question being edited, and the capitalization of the answers was changed... so it no longer matched what the plugin knows about. Just pushed a fix.

**Closed by benjaffe** 2016-02-14 02:10 UTC
